default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mysql
  username: root
  password: root

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: rails_app
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %> 
  host: <%= ENV['RAILS_DB_HOST'] %>
